# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='firsname')),
                ('lastename', models.CharField(max_length=30, verbose_name='lastname')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='phone number')),
                ('birth_data', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date of birthday')),
                ('visit_first_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name=' visit first date')),
                ('male', models.BooleanField(verbose_name='male')),
                ('famale', models.BooleanField(verbose_name='fmale')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('name_skill', models.CharField(max_length=50, verbose_name='name skill')),
                ('profil', models.CharField(max_length=300, null=True, verbose_name='profil')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=50, verbose_name='skill level')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sport', models.CharField(max_length=50, verbose_name='name sport')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='name_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Sport'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Skill'),
        ),
    ]
