# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='family',
            field=models.CharField(default=2, max_length=50, verbose_name='family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='fname',
            field=models.CharField(default=2, max_length=50, verbose_name='fname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Supervisor', verbose_name='supervisor'),
        ),
    ]
