# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='name_sport',
            new_name='namesport',
        ),
    ]
