# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171015_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='firsname')),
                ('lastename', models.CharField(max_length=30, verbose_name='lastname')),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name_skill',
            field=models.CharField(max_length=50, null=True, verbose_name='name skill'),
        ),
    ]
