# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171011_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='developer',
            name='fname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Supervisor', verbose_name='fname'),
            preserve_default=False,
        ),
    ]
