# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20171023_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_data',
            field=models.CharField(max_length=50, null=True, verbose_name='date of birthday'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='visit_first_date',
            field=models.CharField(default=11, max_length=50, verbose_name=' visit first date'),
            preserve_default=False,
        ),
    ]
