# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20171011_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='fname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='task.Supervisor', verbose_name='fname'),
        ),
    ]
