# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20171011_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='developer',
            name='fdname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Supervisor'),
            preserve_default=False,
        ),
    ]
