# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20171023_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='visit_first_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
