# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20171011_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='fname',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='name',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
