# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20171023_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_data',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='famale',
            field=models.CharField(max_length=20, verbose_name='fmale'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='male',
            field=models.CharField(max_length=20, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='visit_first_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
