# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20171011_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lasttname', models.CharField(max_length=50, verbose_name='lastname')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='phonenumber')),
                ('sportfield', models.CharField(max_length=50, verbose_name='sportfield')),
                ('birth_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name=' Date of Birthday ')),
                ('visit_first_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name=' visit_first_date ')),
                ('sex', models.BooleanField(verbose_name='sex')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('skill', models.IntegerField(default=0, verbose_name='Seniority')),
                ('profil', models.CharField(max_length=200, verbose_name='profil')),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='fdname',
        ),
        migrations.RemoveField(
            model_name='taskbar',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='taskbar',
            name='project',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Taskbar',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
