# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20171023_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
