# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20171011_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='skill',
            field=models.IntegerField(default=0, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sportfield',
            field=models.CharField(max_length=1),
        ),
        migrations.AddField(
            model_name='sport',
            name='app_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Athlete', verbose_name='app_sport'),
        ),
    ]
