# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20171011_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sportfield',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='app_sport',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='description',
        ),
        migrations.AddField(
            model_name='athlete',
            name='app_sport',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='task.Sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='name_sport',
            field=models.CharField(default=2, max_length=50, verbose_name='namesport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='name_sport',
            field=models.CharField(default=1, max_length=40, verbose_name='sportname'),
            preserve_default=False,
        ),
    ]
