# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20171028_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_data',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
