# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20171028_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
