# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20171013_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sex', models.CharField(max_length=50, verbose_name='Title')),
                ('sex', models.CharField(max_length=10, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_skill', models.CharField(max_length=50, verbose_name='Title')),
                ('skill_level', models.CharField(max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='name_sport',
        ),
        migrations.AddField(
            model_name='athlete',
            name='id_athlete',
            field=models.CharField(default=1, max_length=30, verbose_name='id_athlate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='id_sport',
            field=models.CharField(default=1, max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profil',
            field=models.CharField(max_length=400, verbose_name='profil'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.BooleanField(verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='skill',
            field=models.IntegerField(verbose_name='Skill'),
        ),
    ]
