# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20171013_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='profil',
        ),
        migrations.AddField(
            model_name='athlete',
            name='profill',
            field=models.CharField(default=1, max_length=400, verbose_name='profill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Sex'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Skill'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='id_sex',
            field=models.CharField(max_length=50, verbose_name='id_sex'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='sex',
            field=models.CharField(max_length=10, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id_skill',
            field=models.CharField(max_length=50, verbose_name='id_skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(max_length=100, verbose_name='skill_level'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='id_sport',
            field=models.CharField(max_length=50, verbose_name='id_sport'),
        ),
    ]
