# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='phonenumber',
            field=models.CharField(max_length=10, verbose_name='phone number'),
        ),
    ]
